language: android
jdk:
 - oraclejdk8

env: 
 global:
  #- ADB_INSTALL_TIMEOUT=20
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  #- EMULATOR_API_LEVEL=24
  #- ANDROID_EMULATOR_IMAGE=sys-img-arm64-v8a-android-24
  #- ANDROID_ABI=arm64-v8a

android:
 licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  #- '.+'
  
 components:
  # Base Components
  - tools
  - platform-tools
  - tools
  # BuildTools version
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  # SDK version
  - android-$ANDROID_API_LEVEL
  #- android-$EMULATOR_API_LEVEL
  # Aditional Components
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-google-google_play_services
  - addon-google_apis-google-$ANDROID_API_LEVEL
  # Emulator
  #- $ANDROID_EMULATOR_IMAGE

before_install:
 # permissao para executar
 - chmod +x gradlew
 # eliminar o warning
 - mkdir -p ~/.android
 - touch ~/.android/repositories.cfg
 
install:
 #- sdkmanager --list || true
 # updates
 #- echo yes | sdkmanager "tools"
 #- echo yes | sdkmanager "platform-tools"
 #- echo yes | sdkmanager "build-tools;"$ANDROID_BUILD_TOOLS_VERSION
 #- echo yes | sdkmanager "platforms;android-"$ANDROID_API_LEVEL # Latest platform required by SDK tools

 #- echo yes | sdkmanager "extras;android;m2repository"
 #- echo yes | sdkmanager "extras;google;m2repository"
 #- echo yes | sdkmanager --update
 #- echo yes | sdkmanager --licenses
 
before_script:
 - mkdir -p "$ANDROID_HOME/licenses"
 - cp ./google-licenses/* "$ANDROID_HOME/licenses"
 #- sdkmanager "system-images;android-$EMULATOR_API_LEVEL;google_apis;$ANDROID_ABI"
 #- echo no | avdmanager -v create avd -f -n test -k "system-images;android-$EMULATOR_API_LEVEL;google_apis;$ANDROID_ABI"
 #- $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -gpu swiftshader &
 #- android-wait-for-emulator
 
script:
 - ./gradlew build check
 #- ./gradlew dependencyCheckAnalyse build
 #- adb shell input keyevent 82
 #- ./gradlew connectedCheck -PdisablePreDex --stacktrace
