language: android

android:
components:
 - tools
 - platform-tools
 - tools
 - build-tools-28.0.3
 - android-28
 - android-25
 - extra-android-support
 - extra-google-m2repository
 - extra-android-m2repository
 - sys-img-armeabi-v7a-google_apis-18

 
before_install:
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-28"
 - yes | sdkmanager "platforms;android-25"
 
before_script:
 - android list targets
 - echo no | android create avd --force -n test -t "system-images;android-25;google_apis;armeabi-v7a"
 - emulator -avd test -no-window &
 - android-wait-for-emulator
 
script:
 - ./gradlew dependencyCheckAnalyse build
 - adb shell input keyevent 82
 - ./gradlew connectedCheck -PdisablePreDex --stacktrace
