language: android
jdk:
 - oraclejdk8

env: 
 global:
  - ADB_INSTALL_TIMEOUT=20

android:
 components:
  - tools
  - platform-tools
  - tools
 
  - build-tools-28.0.3
  - android-28
  - android-24
 
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-google-google_play_services
 
  - sys-img-arm64-v8a-android-24

 
before_install:
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-28"
 - yes | sdkmanager "platforms;android-24"
 
install:
 - sdkmanager --list || true
 
before_script:
 - android list targets
 - sdkmanager "system-images;android-24;google_apis;arm64-v8a"
 - echo no | avdmanager -v create and -f -n teste -k "system-images;android-24;google_apis;arm64-v8a"
 - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
 - android-wait-for-emulator
 
script:
 - ./gradlew dependencyCheckAnalyse build
 - adb shell input keyevent 82
 - ./gradlew connectedCheck -PdisablePreDex --stacktrace
